#!/usr/bin/env python3
"""
Demo analysis and validation script for study: aberdeen-1996-spider-technologies-netdynamics
Generated by Archival Ingest Skill v13
"""

import csv
import os
import sys
from collections import defaultdict

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, '..', 'data')


def load_csv(filename):
    path = os.path.join(DATA, filename)
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def main():
    print("=" * 60)
    print(f"Study: aberdeen-1996-spider-technologies-netdynamics")
    print("=" * 60)

    studies      = load_csv('studies.csv')
    entities     = load_csv('entities.csv')
    technologies = load_csv('technologies.csv')
    observations = load_csv('observations.csv')
    codes        = load_csv('codes.csv')

    # 1. Study summary
    s = studies[0]
    print(f"\n[STUDY SUMMARY]")
    print(f"  Title:      {s['title']}")
    print(f"  Author:     {s['author']}")
    print(f"  Date:       {s['date']}")
    print(f"  Importance: {s['importance']}")
    print(f"  Relevance:  {s['relevance']}")
    print(f"  Prescience: {s['prescience']}")

    # 2. Row counts
    print(f"\n[ROW COUNTS]")
    print(f"  Entities:     {len(entities)}")
    print(f"  Technologies: {len(technologies)}")
    print(f"  Observations: {len(observations)}")
    print(f"  Codes:        {len(codes)}")

    # 3. Observation type distribution
    print(f"\n[OBSERVATION TYPES]")
    type_counts = defaultdict(int)
    for o in observations:
        type_counts[o['observation_type']] += 1
    for t, c in sorted(type_counts.items()):
        print(f"  {t}: {c}")

    # 4. Referential integrity checks
    print(f"\n[REFERENTIAL INTEGRITY]")
    entity_ids = {e['entity_id'] for e in entities} | {''}
    tech_ids   = {t['tech_id'] for t in technologies} | {''}
    code_ids   = {c['code_id'] for c in codes}

    obs_entity_errors = [o['obs_id'] for o in observations if o['entity_id'] not in entity_ids]
    obs_tech_errors   = [o['obs_id'] for o in observations if o['tech_id'] not in tech_ids]
    obs_type_errors   = [o['obs_id'] for o in observations if o['observation_type'] not in code_ids]
    obs_meth_errors   = [o['obs_id'] for o in observations if o['methodology_code'] not in code_ids]

    passed = True
    if obs_entity_errors:
        print(f"  [FAIL] Missing entity_ids: {obs_entity_errors}")
        passed = False
    else:
        print(f"  [PASS] All entity_id references valid")

    if obs_tech_errors:
        print(f"  [FAIL] Missing tech_ids: {obs_tech_errors}")
        passed = False
    else:
        print(f"  [PASS] All tech_id references valid")

    if obs_type_errors:
        print(f"  [FAIL] Unknown observation_types: {obs_type_errors}")
        passed = False
    else:
        print(f"  [PASS] All observation_type codes valid")

    if obs_meth_errors:
        print(f"  [FAIL] Unknown methodology_codes: {obs_meth_errors}")
        passed = False
    else:
        print(f"  [PASS] All methodology_code references valid")

    # 5. Prediction accuracy
    predictions = [o for o in observations if o['observation_type'] == 'viability-prediction']
    outcomes    = [o for o in observations if o['observation_type'] == 'actual-outcome']

    print(f"\n[PREDICTION ANALYSIS]")
    print(f"  Viability predictions: {len(predictions)}")
    print(f"  Actual outcomes:       {len(outcomes)}")
    if predictions and outcomes:
        verified_outcomes = [o for o in outcomes if o['confidence'] == 'verified']
        ratio = len(verified_outcomes) / len(predictions) if predictions else 0
        print(f"  Verified outcomes:     {len(verified_outcomes)}")
        print(f"  Coverage ratio:        {ratio:.0%}")

    # 6. Final verdict
    print(f"\n[VALIDATION RESULT]")
    if passed:
        print("  ALL CHECKS PASSED")
    else:
        print("  SOME CHECKS FAILED — see above")
        sys.exit(1)


if __name__ == '__main__':
    main()
