"""
demo_analysis.py — Validation and analysis script
Study: aberdeen-1996-computer-telephony-integration
(Actual content: Internet Architecture: Prescription For Success)
Generated by Archival Ingest Skill v13
"""
import csv
import os

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, "..", "data")


def load_csv(filename):
    path = os.path.join(DATA, filename)
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main():
    studies = load_csv("studies.csv")
    entities = load_csv("entities.csv")
    technologies = load_csv("technologies.csv")
    observations = load_csv("observations.csv")
    codes = load_csv("codes.csv")

    print("=" * 60)
    print("STUDY SUMMARY")
    print("=" * 60)
    s = studies[0]
    print(f"  Title     : {s['title']}")
    print(f"  Date      : {s['date']}")
    print(f"  Importance: {s['importance']}")
    print(f"  Relevance : {s['relevance']}")
    print(f"  Prescience: {s['prescience']}")

    print("\n" + "=" * 60)
    print("TABLE ROW COUNTS")
    print("=" * 60)
    for name, tbl in [("Studies", studies), ("Entities", entities),
                      ("Technologies", technologies), ("Observations", observations), ("Codes", codes)]:
        print(f"  {name:<15}: {len(tbl)}")

    print("\n" + "=" * 60)
    print("OBSERVATION TYPE BREAKDOWN")
    print("=" * 60)
    counts = {}
    for o in observations:
        counts[o["observation_type"]] = counts.get(o["observation_type"], 0) + 1
    for k, v in sorted(counts.items()):
        print(f"  {k:<30} {v}")

    print("\n" + "=" * 60)
    print("REFERENTIAL INTEGRITY CHECK")
    print("=" * 60)
    entity_ids = {e["entity_id"] for e in entities}
    tech_ids = {t["tech_id"] for t in technologies}
    code_ids = {c["code_id"] for c in codes}
    errors = 0
    for o in observations:
        for field, valid_set in [("entity_id", entity_ids), ("tech_id", tech_ids),
                                  ("methodology_code", code_ids), ("observation_type", code_ids)]:
            val = o[field]
            if val and val not in valid_set:
                print(f"  [ERROR] {o['obs_id']}: {field}='{val}' not found")
                errors += 1
    if errors == 0:
        print("  All referential integrity checks PASSED.")

    print("\n" + "=" * 60)
    print("PREDICTION ACCURACY")
    print("=" * 60)
    preds = [o for o in observations if o["observation_type"] == "viability-prediction"]
    outcomes = [o for o in observations if o["observation_type"] == "actual-outcome"]
    verified = [o for o in outcomes if o["confidence"] == "verified"]
    print(f"  Predictions: {len(preds)}, Outcomes: {len(outcomes)}, Verified: {len(verified)}")
    if preds:
        print(f"  Accuracy: {len(verified)/len(preds)*100:.0f}%")
    for p in preds:
        print(f"  - [{p['year_observed']}] {p['metric_name'][:70]}")


if __name__ == "__main__":
    main()
