#!/usr/bin/env python3
"""
Demo Analysis Script
Study: aberdeen-1996-hp-praesidium-family
Generated by Archival Ingest Skill v13
"""

import csv
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, "..", "data")

def load_csv(filename):
    filepath = os.path.join(DATA, filename)
    with open(filepath, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def main():
    print("=" * 60)
    print(f"STUDY: aberdeen-1996-hp-praesidium-family")
    print("=" * 60)

    studies = load_csv("studies.csv")
    entities = load_csv("entities.csv")
    techs = load_csv("technologies.csv")
    obs = load_csv("observations.csv")
    codes = load_csv("codes.csv")

    study = studies[0]
    print(f"\nTitle: {study['title']}")
    print(f"Author: {study['author']}")
    print(f"Date: {study['date']}")
    print(f"Importance: {study['importance']} | Relevance: {study['relevance']} | Prescience: {study['prescience']}")

    print(f"\nTable counts:")
    print(f"  Entities: {len(entities)}")
    print(f"  Technologies: {len(techs)}")
    print(f"  Observations: {len(obs)}")
    print(f"  Codes: {len(codes)}")

    # Observation type breakdown
    print("\nObservation types:")
    type_counts = {}
    for o in obs:
        ot = o["observation_type"]
        type_counts[ot] = type_counts.get(ot, 0) + 1
    for k, v in sorted(type_counts.items()):
        print(f"  {k}: {v}")

    # Referential integrity checks
    print("\nReferential integrity checks:")
    entity_ids = {e["entity_id"] for e in entities} | {""}
    tech_ids = {t["tech_id"] for t in techs} | {""}
    code_ids = {c["code_id"] for c in codes}

    errors = []
    for o in obs:
        if o["entity_id"] and o["entity_id"] not in entity_ids:
            errors.append(f"  MISSING entity_id: {o['entity_id']} in {o['obs_id']}")
        if o["tech_id"] and o["tech_id"] not in tech_ids:
            errors.append(f"  MISSING tech_id: {o['tech_id']} in {o['obs_id']}")
        if o["observation_type"] not in code_ids:
            errors.append(f"  MISSING obs type code: {o['observation_type']} in {o['obs_id']}")

    if errors:
        print("  ERRORS:")
        for e in errors:
            print(e)
    else:
        print("  All referential integrity checks PASSED")

    # Prediction accuracy
    predictions = [o for o in obs if o["observation_type"] == "viability-prediction"]
    outcomes = [o for o in obs if o["observation_type"] == "actual-outcome"]
    print(f"\nPrediction accuracy:")
    print(f"  Predictions: {len(predictions)}")
    print(f"  Matched outcomes: {len(outcomes)}")
    verified = [o for o in outcomes if o["confidence"] == "verified"]
    print(f"  Verified outcomes: {len(verified)}")

    print("\n" + "=" * 60)
    print("Analysis complete.")

if __name__ == "__main__":
    main()
