"""
demo_analysis.py — Validation and analysis script
Study: aberdeen-1996-network-appliance-data-appliances
Generated by Archival Ingest Skill v13
"""
import csv
import os

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, "..", "data")


def load_csv(filename):
    path = os.path.join(DATA, filename)
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main():
    studies = load_csv("studies.csv")
    entities = load_csv("entities.csv")
    technologies = load_csv("technologies.csv")
    observations = load_csv("observations.csv")
    codes = load_csv("codes.csv")

    print("=" * 60)
    print("STUDY SUMMARY")
    print("=" * 60)
    s = studies[0]
    print(f"  Title     : {s['title']}")
    print(f"  Author    : {s['author']}")
    print(f"  Date      : {s['date']}")
    print(f"  Importance: {s['importance']}")
    print(f"  Relevance : {s['relevance']}")
    print(f"  Prescience: {s['prescience']}")

    print("\n" + "=" * 60)
    print("TABLE ROW COUNTS")
    print("=" * 60)
    print(f"  Studies      : {len(studies)}")
    print(f"  Entities     : {len(entities)}")
    print(f"  Technologies : {len(technologies)}")
    print(f"  Observations : {len(observations)}")
    print(f"  Codes        : {len(codes)}")

    print("\n" + "=" * 60)
    print("REVENUE TRAJECTORY (market-data observations)")
    print("=" * 60)
    rev = [o for o in observations if o["observation_type"] == "market-data"]
    for r in sorted(rev, key=lambda x: x["year_observed"]):
        print(f"  {r['year_observed']}: {r['metric_value']}")

    print("\n" + "=" * 60)
    print("REFERENTIAL INTEGRITY CHECK")
    print("=" * 60)
    entity_ids = {e["entity_id"] for e in entities}
    tech_ids = {t["tech_id"] for t in technologies}
    code_ids = {c["code_id"] for c in codes}
    errors = 0
    for o in observations:
        eid = o["entity_id"]
        tid = o["tech_id"]
        mc = o["methodology_code"]
        ot = o["observation_type"]
        if eid and eid not in entity_ids:
            print(f"  [ERROR] {o['obs_id']}: entity_id '{eid}' missing")
            errors += 1
        if tid and tid not in tech_ids:
            print(f"  [ERROR] {o['obs_id']}: tech_id '{tid}' missing")
            errors += 1
        if mc and mc not in code_ids:
            print(f"  [ERROR] {o['obs_id']}: methodology_code '{mc}' missing")
            errors += 1
        if ot and ot not in code_ids:
            print(f"  [ERROR] {o['obs_id']}: observation_type '{ot}' missing")
            errors += 1
    if errors == 0:
        print("  All referential integrity checks PASSED.")
    else:
        print(f"  {errors} error(s) found.")

    print("\n" + "=" * 60)
    print("PREDICTION ACCURACY")
    print("=" * 60)
    preds = [o for o in observations if o["observation_type"] == "viability-prediction"]
    outcomes = [o for o in observations if o["observation_type"] == "actual-outcome"]
    verified = [o for o in outcomes if o["confidence"] == "verified"]
    print(f"  Predictions : {len(preds)}")
    print(f"  Outcomes    : {len(outcomes)}")
    print(f"  Verified    : {len(verified)}")
    if preds:
        print(f"  Accuracy    : {len(verified)/len(preds)*100:.0f}%")


if __name__ == "__main__":
    main()
