"""
Generate all CSV files for the Aberdeen Group study:
3Com's LANplex 2500: Profiling the Consummate Ethernet/FDDI Workgroup Switch
study_id: aberdeen-1995-3com-lanplex-2500
"""

import csv
import os

STUDY_ID = "aberdeen-1995-3com-lanplex-2500"
OUT = "/home/user/workspace/output/aberdeen-1995-3com-lanplex-2500/data"
os.makedirs(OUT, exist_ok=True)

ABSTRACT = (
    "This Aberdeen Group product profile, published September 1995, evaluates 3Com's LANplex 2500 "
    "Ethernet/FDDI workgroup switch approximately nine months after its December 1994 market introduction. "
    "Using primary user research across hospitals, financial institutions, universities, and manufacturing firms, "
    "combined with competitive analysis against Cisco Systems, Bay Networks, and ALANTEC, Aberdeen assessed "
    "the 2500's technical architecture, ISE-chip ASIC performance (565K pps forwarding rate), management "
    "capabilities (RMON, Transcend Enterprise Manager), and investment-protection roadmap. "
    "Key findings confirm the LANplex 2500 as the market's most capable Ethernet/FDDI workgroup switch at its "
    "price point, outperforming competitors on switching performance, feature set, and modular design while "
    "leveraging 3Com's established LANplex 6000 installed base. "
    "The study predicts that Fast Ethernet (100BaseTX) and OC-3 ATM uplink cards will ship in Q1 1996, "
    "that FDDI backbones will remain prominent in enterprise planning through the mid-1990s, and that "
    "3Com's 6-to-9-month competitive lead is under pressure as rivals intensify development efforts. "
    "The report frames these findings within 3Com's three-stage High-Performance Scalable Networking (HPSN) "
    "vision, positioning the LANplex 2500 as Stage 2 of a migration path from collapsed backbones through "
    "distributed LAN switching toward eventual ATM adoption."
)

# ── studies.csv ──────────────────────────────────────────────────────────────
with open(f"{OUT}/studies.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=[
        "study_id","title","author","date","type","subject_domain",
        "methodology","source_file","abstract","license"
    ])
    w.writeheader()
    w.writerow({
        "study_id": STUDY_ID,
        "title": "3Com's LANplex 2500: Profiling the Consummate Ethernet/FDDI Workgroup Switch",
        "author": "Aberdeen Group",
        "date": "1995-09-01",
        "type": "product-profile",
        "subject_domain": "LAN-switching",
        "methodology": "product-profiling, user-research, competitive-analysis",
        "source_file": "1995-3Com_s-LANplex-2500_-Profiling-the-Consummate-Ethernet_FDDI-Workgroup-Switch-pr.pdf",
        "abstract": ABSTRACT,
        "license": "CC-BY-4.0",
    })
print("studies.csv written")

# ── entities.csv ─────────────────────────────────────────────────────────────
entities = [
    {
        "entity_id": "3com",
        "entity_name": "3Com Corporation",
        "entity_type": "company",
        "sector": "networking-hardware",
        "status": "acquired",
        "successor": "HP/HPE (acquired 2010)",
        "years_active": "1979-2010",
        "study_id": STUDY_ID,
        "notes": "Headquarters: Santa Clara, CA. Switching Division in Boxborough, MA. Acquired Synernetics 1993.",
    },
    {
        "entity_id": "cisco-systems",
        "entity_name": "Cisco Systems",
        "entity_type": "company",
        "sector": "networking-hardware",
        "status": "active",
        "successor": "",
        "years_active": "1984-present",
        "study_id": STUDY_ID,
        "notes": "Primary competitor in Ethernet/FDDI switching market at time of study.",
    },
    {
        "entity_id": "alantec",
        "entity_name": "ALANTEC Corporation",
        "entity_type": "company",
        "sector": "networking-hardware",
        "status": "acquired",
        "successor": "Fore Systems (1996), then Marconi, then Ericsson",
        "years_active": "1992-1996",
        "study_id": STUDY_ID,
        "notes": "LAN switching competitor cited in competitive table. Acquired by Fore Systems 1996.",
    },
    {
        "entity_id": "bay-networks",
        "entity_name": "Bay Networks",
        "entity_type": "company",
        "sector": "networking-hardware",
        "status": "acquired",
        "successor": "Nortel Networks (acquired 1998)",
        "years_active": "1994-1998",
        "study_id": STUDY_ID,
        "notes": "Formed from merger of SynOptics and Wellfleet Communications in 1994.",
    },
    {
        "entity_id": "synernetics",
        "entity_name": "Synernetics, Inc.",
        "entity_type": "company",
        "sector": "networking-hardware",
        "status": "acquired",
        "successor": "3Com Corporation (acquired 1993)",
        "years_active": "1990-1993",
        "study_id": STUDY_ID,
        "notes": "Fast-moving LAN switching startup; expertise in high-performance FDDI backbone switching. Formed core of 3Com Switching Division.",
    },
    {
        "entity_id": "aberdeen-group",
        "entity_name": "Aberdeen Group, Inc.",
        "entity_type": "firm",
        "sector": "market-research",
        "status": "acquired",
        "successor": "Harte-Hanks (acquired 2001); brand later acquired by Aberdeen Strategy & Research",
        "years_active": "1988-2001",
        "study_id": STUDY_ID,
        "notes": "One Boston Place, Boston MA 02108. Contact: Chris Stevenson.",
    },
    {
        "entity_id": "hp",
        "entity_name": "Hewlett-Packard Company",
        "entity_type": "company",
        "sector": "technology",
        "status": "active",
        "successor": "HP Inc. / HPE (split 2015)",
        "years_active": "1939-present",
        "study_id": STUDY_ID,
        "notes": "Supported as enterprise management platform via Transcend Enterprise Manager.",
    },
    {
        "entity_id": "sun-microsystems",
        "entity_name": "Sun Microsystems",
        "entity_type": "company",
        "sector": "technology",
        "status": "acquired",
        "successor": "Oracle Corporation (acquired 2010)",
        "years_active": "1982-2010",
        "study_id": STUDY_ID,
        "notes": "Supported as enterprise management platform via Transcend Enterprise Manager.",
    },
    {
        "entity_id": "ibm",
        "entity_name": "IBM",
        "entity_type": "company",
        "sector": "technology",
        "status": "active",
        "successor": "",
        "years_active": "1911-present",
        "study_id": STUDY_ID,
        "notes": "Supported as enterprise management platform via Transcend Enterprise Manager.",
    },
]

with open(f"{OUT}/entities.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=[
        "entity_id","entity_name","entity_type","sector","status",
        "successor","years_active","study_id","notes"
    ])
    w.writeheader()
    w.writerows(entities)
print("entities.csv written")

# ── technologies.csv ─────────────────────────────────────────────────────────
technologies = [
    {
        "tech_id": "fddi",
        "tech_name": "FDDI (Fiber Distributed Data Interface)",
        "category": "protocol",
        "vendor": "ANSI standard",
        "era": "1987-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "100 Mbps token-ring LAN standard; prominent as campus backbone technology at time of study.",
    },
    {
        "tech_id": "ethernet-switching",
        "tech_name": "Ethernet Switching",
        "category": "protocol",
        "vendor": "multi-vendor",
        "era": "1993-present",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "active",
        "study_id": STUDY_ID,
        "notes": "Layer-2 frame switching for 10 Mbps Ethernet segments; evolved through Fast, Gigabit, 10GbE, etc.",
    },
    {
        "tech_id": "atm",
        "tech_name": "ATM (Asynchronous Transfer Mode)",
        "category": "protocol",
        "vendor": "ITU/ATM Forum standard",
        "era": "1988-2005",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Cell-based switching technology positioned as future backbone. OC-3 (155 Mbps) UNI targeted for LANplex 2500 uplink in Q1 1996.",
    },
    {
        "tech_id": "fast-ethernet-100basetx",
        "tech_name": "Fast Ethernet (100BaseTX)",
        "category": "protocol",
        "vendor": "IEEE 802.3u standard",
        "era": "1995-2010",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "legacy-supported",
        "study_id": STUDY_ID,
        "notes": "100 Mbps over twisted-pair copper; uplink card for LANplex 2500 expected Q1 1996.",
    },
    {
        "tech_id": "ise-chip",
        "tech_name": "ISE-Chip (Intelligent Switching Engine ASIC)",
        "category": "platform",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "3Com proprietary ASIC delivering 565K pps forwarding. Front-end engine to RISC processor, creating 'fast path' architecture.",
    },
    {
        "tech_id": "rmon",
        "tech_name": "RMON (Remote Network Monitoring)",
        "category": "protocol",
        "vendor": "IETF (RFC 1271/RFC 1757)",
        "era": "1992-2010",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "legacy-supported",
        "study_id": STUDY_ID,
        "notes": "3Com's Roving Analysis Port implemented distributed RMON across all ports. Cisco supported RFC 1271.",
    },
    {
        "tech_id": "hpsn",
        "tech_name": "HPSN (High-Performance Scalable Networking)",
        "category": "framework",
        "vendor": "3Com",
        "era": "1994-1998",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "3Com's 3-stage networking vision: Stage 1=collapsed backbone, Stage 2=distributed LAN switches, Stage 3=ATM migration.",
    },
    {
        "tech_id": "lanplex-2500",
        "tech_name": "LANplex 2500",
        "category": "platform",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "16-port 10 Mbps Ethernet + 2 FDDI ports. Modular workgroup switch. ISE-chip ASIC. Introduced December 1994.",
    },
    {
        "tech_id": "lanplex-6000",
        "tech_name": "LANplex 6000",
        "category": "platform",
        "vendor": "3Com",
        "era": "1993-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "3Com flagship backbone switch. Market leader in backbone switching at time of study. Larger FDDI concentration capacity than 2500.",
    },
    {
        "tech_id": "linkswitch-2200",
        "tech_name": "LinkSwitch 2200",
        "category": "platform",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "16-port Ethernet switch with single FDDI port. LANplex technology repackaged in 3Com SuperStack form factor for SMB market.",
    },
    {
        "tech_id": "cellplex",
        "tech_name": "CELLplex",
        "category": "platform",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "3Com ATM workgroup and backbone switch family. Separate from LANplex family.",
    },
    {
        "tech_id": "transcend-enterprise-manager",
        "tech_name": "Transcend Enterprise Manager",
        "category": "application",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Flagship network management application. Supported HP OpenView, Sun NetManager, and IBM NetView platforms. Windows version expected Q4 1995.",
    },
    {
        "tech_id": "virtual-lan",
        "tech_name": "Virtual LAN (VLAN)",
        "category": "protocol",
        "vendor": "multi-vendor",
        "era": "1995-present",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "active",
        "study_id": STUDY_ID,
        "notes": "LANplex 2500 supported VLANs via port groups and MAC address groups. Cited as key user requirement.",
    },
    {
        "tech_id": "elastic-packet-buffering",
        "tech_name": "Elastic Packet Buffering",
        "category": "platform",
        "vendor": "3Com",
        "era": "1994-2000",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "3Com proprietary buffering approach: guaranteed minimum buffers per port, dynamic expansion as needed. Reduces packet drops under contention.",
    },
]

with open(f"{OUT}/technologies.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=[
        "tech_id","tech_name","category","vendor","era",
        "lifecycle_at_study","lifecycle_current","study_id","notes"
    ])
    w.writeheader()
    w.writerows(technologies)
print("technologies.csv written")

# ── observations.csv ─────────────────────────────────────────────────────────
observations = [
    # Market position / competitive
    {
        "obs_id": f"{STUDY_ID}-OBS-001",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "Market position — Ethernet/FDDI workgroup switch",
        "metric_value": "Feature-rich and aggressively priced; most capable offering vs. Cisco and ALANTEC",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.1 Executive Summary",
        "notes": "Aberdeen states 2500 is 'unlike other Ethernet/FDDI switches available from Cisco Systems and ALANTEC' in feature richness and pricing.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-002",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "benchmark-result",
        "year_observed": "1995",
        "metric_name": "Packet forwarding rate",
        "metric_value": "565,000 pps (packets per second)",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "Achieved via ISE-chip ASIC + dual RISC processors. Aberdeen states this puts LANplex 2500 'well ahead of competitive offerings from Cisco, Bay and ALANTEC'.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-003",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "Competitive lead duration",
        "metric_value": "6 to 9 months ahead on performance and features",
        "confidence": "medium",
        "methodology_code": "competitive-profiling",
        "source_page": "p.1 Executive Summary",
        "notes": "Aberdeen notes competition is intensifying, cutting into 3Com's lead.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-004",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-6000",
        "observation_type": "market-data",
        "year_observed": "1995",
        "metric_name": "LANplex 6000 market position",
        "metric_value": "Backbone switching market leader",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "Even new 2500 customers gained credibility via 3Com's established LANplex 6000 market leadership.",
    },
    # ISE-chip / ASIC architecture
    {
        "obs_id": f"{STUDY_ID}-OBS-005",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "ise-chip",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "ISE-chip ASIC design principle",
        "metric_value": "ASIC front-end 'fast path' + dual RISC processors; repetitive packet processing in ASIC, intelligent functions in RISC",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "Design reduces component count, improving reliability. No central processing engine ensures performance scales with new features.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-006",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "ise-chip",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "ISE-chip rollout plan",
        "metric_value": "Introduced first in LANplex 2500; next to be added to LANplex 6000",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "ISE-chip ASIC is new to the LANplex family starting with the 2500.",
    },
    # HPSN 3-stage vision
    {
        "obs_id": f"{STUDY_ID}-OBS-007",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "hpsn",
        "observation_type": "framework-factor",
        "year_observed": "1995",
        "metric_name": "HPSN Stage 1",
        "metric_value": "Collapsed backbone with server farm consolidation in data center; complex functions centralized in router",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 3Com Vision in Place",
        "notes": "Stage 1 of 3Com's three-stage High-Performance Scalable Networking vision.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-008",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "hpsn",
        "observation_type": "framework-factor",
        "year_observed": "1995",
        "metric_name": "HPSN Stage 2",
        "metric_value": "Distributed LAN switches in wiring closets; FDDI and Fast Ethernet high-speed links to servers and desktops",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 3Com Vision in Place",
        "notes": "LANplex 2500 is the Stage 2 deliverable. High-speed uplinks include FDDI and Fast Ethernet.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-009",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "hpsn",
        "observation_type": "framework-factor",
        "year_observed": "1995",
        "metric_name": "HPSN Stage 3",
        "metric_value": "ATM migration beginning with campus backbone, extended to buildings where cost/performance justifies",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 3Com Vision in Place",
        "notes": "Stage 3 is the planned ATM migration endpoint of the HPSN vision.",
    },
    # ATM migration predictions
    {
        "obs_id": f"{STUDY_ID}-OBS-010",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "atm",
        "observation_type": "viability-prediction",
        "year_observed": "1996",
        "metric_name": "OC-3 ATM uplink card for LANplex 2500 — ship date prediction",
        "metric_value": "Q1 1996",
        "confidence": "medium",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Growth Path Is Addressed",
        "notes": "OC-3 uplink with LAN emulation and UNI connectivity software projected for Q1 1996.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-011",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "atm",
        "observation_type": "viability-prediction",
        "year_observed": "1996",
        "metric_name": "Enterprise ATM backbone adoption timeline",
        "metric_value": "Users plan ATM backbone implementation in 1996 timeframe",
        "confidence": "medium",
        "methodology_code": "user-research",
        "source_page": "p.2 Growth Path Is Addressed",
        "notes": "Based on interviews with 2500 users; number of users noted 1996 ATM backbone plans.",
    },
    # Fast Ethernet prediction
    {
        "obs_id": f"{STUDY_ID}-OBS-012",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "fast-ethernet-100basetx",
        "observation_type": "viability-prediction",
        "year_observed": "1996",
        "metric_name": "Fast Ethernet (100BaseTX) uplink card for LANplex 2500 — ship date prediction",
        "metric_value": "Early 1996 (Q1)",
        "confidence": "medium",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Growth Path Is Addressed",
        "notes": "Users noted strong interest in Fast Ethernet card expected to ship by early 1996.",
    },
    # FDDI backbone prominence
    {
        "obs_id": f"{STUDY_ID}-OBS-013",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "fddi",
        "observation_type": "market-data",
        "year_observed": "1995",
        "metric_name": "FDDI campus backbone status in enterprise planning",
        "metric_value": "Still prominent as active deliverable on planning agendas of many large enterprises",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.1 Preface",
        "notes": "Despite ATM excitement and increased shipments, FDDI remains the dominant campus backbone technology.",
    },
    # User perspectives on stability
    {
        "obs_id": f"{STUDY_ID}-OBS-014",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "User assessment of product stability",
        "metric_value": "LANplex 2500 'came through in these environments with flying colors'",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.3 Conclusion",
        "notes": "Product stability is a big issue for users needing to quickly drop switch into production environments. Aberdeen user quotes: 'there is no convenient time to take our network down.'",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-015",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "User requirement: flash PROM upgradability",
        "metric_value": "Device must be fully flash PROM and fully downloadable from central site; no forklift upgrades acceptable",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.2 Meeting User Expectations",
        "notes": "LANplex 2500 meets this requirement per Aberdeen user interviews.",
    },
    # Competitive table observations
    {
        "obs_id": f"{STUDY_ID}-OBS-016",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "benchmark-result",
        "year_observed": "1995",
        "metric_name": "Competitive table — Switching capability",
        "metric_value": "Ethernet, FDDI, 565K pps (3Com) vs. IP/IPX routing with AT in Q3'95 (Cisco) vs. superior but not as complete as Cisco (Bay/ALANTEC)",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Table 1",
        "notes": "Source: Aberdeen Group competitive table, September 1995.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-017",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "benchmark-result",
        "year_observed": "1995",
        "metric_name": "Competitive table — Routing",
        "metric_value": "3Com: IP routing available; Cisco: IP/IPX routing with AT in Q3'95; Bay: will have key routing protocols like ALANTEC",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Table 1",
        "notes": "Routing capabilities comparison across major competitors.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-018",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "benchmark-result",
        "year_observed": "1995",
        "metric_name": "Competitive table — Uplinks",
        "metric_value": "3Com: FDDI today + Fast Ethernet and ATM; Cisco: ambitious timeframe; Bay/ALANTEC: all players have indicated support",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Table 1",
        "notes": "Uplink roadmap comparison for Fast Ethernet and ATM uplink support.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-019",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "benchmark-result",
        "year_observed": "1995",
        "metric_name": "Competitive table — Reliability",
        "metric_value": "3Com: redundant power and hot-swap modules; Cisco and 3Com appear stronger on reliability",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Table 1",
        "notes": "Redundant power supply and hot-swap modules cited as reliability advantage.",
    },
    # Acquisition / company history
    {
        "obs_id": f"{STUDY_ID}-OBS-020",
        "study_id": STUDY_ID,
        "entity_id": "synernetics",
        "tech_id": "",
        "observation_type": "actual-outcome",
        "year_observed": "1993",
        "metric_name": "Synernetics acquisition by 3Com",
        "metric_value": "Acquired 1993; formed core of 3Com Switching Division",
        "confidence": "verified",
        "methodology_code": "document-review",
        "source_page": "p.1 3Com Vision in Place",
        "notes": "Synernetics' expertise in high-performance FDDI backbone switching formed the foundation of 3Com's LANplex family.",
    },
    # LANplex 2500 specs
    {
        "obs_id": f"{STUDY_ID}-OBS-021",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "LANplex 2500 port configuration",
        "metric_value": "Up to 16 switched 10 Mbps Ethernet ports and 2 switched FDDI ports",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Introducing the LANplex 2500",
        "notes": "Modular, intelligent workgroup switch. Growth path to Fast Ethernet and ATM.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-022",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "LANplex 2500 IP fragmentation capability",
        "metric_value": "Breaks FDDI packets (max 4500 bytes) into Ethernet frames (max 1500 bytes) for FDDI-to-Ethernet translation",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "Critical for high-performance server farms driving wire-speed links across FDDI/Ethernet boundary.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-023",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "elastic-packet-buffering",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "Elastic Packet Buffering design",
        "metric_value": "Guaranteed minimum buffers per port with dynamic expansion; reduces packet drops under port contention",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Built on Intelligence",
        "notes": "User-defined packet filtering also enables traffic control based on thresholds and specific characteristics.",
    },
    # Management / RMON
    {
        "obs_id": f"{STUDY_ID}-OBS-024",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "rmon",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "RMON implementation — Roving Analysis Port",
        "metric_value": "Any port can be designated a roving RMON port; unlimited roving ports per switch; works across multiple switches",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2-3 Building the Management Infrastructure",
        "notes": "Distinguished from typical single-port RMON. 3Com also supports standard RMON from external hardware/software sources.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-025",
        "study_id": STUDY_ID,
        "entity_id": "cisco-systems",
        "tech_id": "rmon",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "Cisco RMON capability",
        "metric_value": "RFC 1271 support enabling RMON access across all ports; developing in-box RMON agent",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.3 Building the Management Infrastructure",
        "notes": "Aberdeen states this capability is 'important' and 3Com has recognized the need for software-based RMON in-box.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-026",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "transcend-enterprise-manager",
        "observation_type": "viability-prediction",
        "year_observed": "1995",
        "metric_name": "Transcend Enterprise Manager — Windows version ship date",
        "metric_value": "Q4 1995",
        "confidence": "medium",
        "methodology_code": "product-profiling",
        "source_page": "p.2 Building the Management Infrastructure",
        "notes": "Flagship management app already supported HP, Sun, and IBM platform solutions.",
    },
    # Telnet / Cisco competitive
    {
        "obs_id": f"{STUDY_ID}-OBS-027",
        "study_id": STUDY_ID,
        "entity_id": "cisco-systems",
        "tech_id": "",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "Cisco defensive position on telnet support",
        "metric_value": "Telnet server connectivity requirement puts Cisco on the defensive; 3Com lead expected to be short-lived",
        "confidence": "medium",
        "methodology_code": "competitive-profiling",
        "source_page": "p.2 Building the Management Infrastructure",
        "notes": "User demand for telnet-based troubleshooting and software downline loading cited as competitive differentiator for 3Com.",
    },
    # User deployment scenarios
    {
        "obs_id": f"{STUDY_ID}-OBS-028",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "Primary deployment scenario",
        "metric_value": "Switched Ethernet client connections to FDDI-based servers on campus backbone; replaces expensive router-based FDDI connections",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.2 User Perspectives",
        "notes": "Users deploy 2500 in hospitals, financial institutions, universities, and manufacturing companies.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-029",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "Secondary deployment scenario",
        "metric_value": "Isolated server traffic on separate backbone using second FDDI port; departmental backbone with local servers",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.2 User Perspectives",
        "notes": "Wiring hub floor devices often connected directly to 2500 via its multiple MAC address capabilities.",
    },
    # LinkSwitch 2200
    {
        "obs_id": f"{STUDY_ID}-OBS-030",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "linkswitch-2200",
        "observation_type": "technology-assessment",
        "year_observed": "1995",
        "metric_name": "LinkSwitch 2200 market positioning",
        "metric_value": "LANplex technology repackaged in SuperStack form factor for SMB/stackable segment",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Switching Explosion",
        "notes": "16-port Ethernet switch with single FDDI port. Low-cost alternative to LANplex 2500 leveraging same ASIC technology.",
    },
    # Virtual LAN requirement
    {
        "obs_id": f"{STUDY_ID}-OBS-031",
        "study_id": STUDY_ID,
        "entity_id": "",
        "tech_id": "virtual-lan",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "VLAN as user requirement",
        "metric_value": "Virtual Networking cited for security, bandwidth management, and ease of moves/adds/changes",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.2 Meeting User Expectations",
        "notes": "LANplex 2500 supports VLANs via port groups and MAC address groups. IP/IPX/AppleTalk intranetworking routing software included.",
    },
    # 3Com's ASIC strategy
    {
        "obs_id": f"{STUDY_ID}-OBS-032",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "ise-chip",
        "observation_type": "strategy-classification",
        "year_observed": "1995",
        "metric_name": "3Com ASIC strategy classification",
        "metric_value": "Technology leadership through proprietary ASIC development; fewer components, higher reliability, better price/performance",
        "confidence": "high",
        "methodology_code": "competitive-profiling",
        "source_page": "p.1 3Com Vision in Place",
        "notes": "3Com 'took a leadership role in switching by pushing the technology envelope, moving aggressively to ASIC technology.'",
    },
    # Early customer base / installed base leverage
    {
        "obs_id": f"{STUDY_ID}-OBS-033",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "market-data",
        "year_observed": "1995",
        "metric_name": "Early customer base leverage",
        "metric_value": "Large number of early 2500 customers had existing LANplex 6000 installations or were evaluating 6000",
        "confidence": "high",
        "methodology_code": "user-research",
        "source_page": "p.2 (top)",
        "notes": "Attractive 2500 price/performance pushed 6000-leaning users to install 2500 even as new product in early 1995.",
    },
    # Conclusion / overall assessment
    {
        "obs_id": f"{STUDY_ID}-OBS-034",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "expert-opinion",
        "year_observed": "1995",
        "metric_name": "Aberdeen overall verdict",
        "metric_value": "LANplex 2500 has met and fully exceeded its promise as excellent workgroup solution and flagship revenue performer for 3Com Switching Division",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.3 Conclusion",
        "notes": "Aberdeen notes product is 'doing extremely well in the market' and has built its own identity independent of the LANplex 6000.",
    },
    {
        "obs_id": f"{STUDY_ID}-OBS-035",
        "study_id": STUDY_ID,
        "entity_id": "3com",
        "tech_id": "lanplex-2500",
        "observation_type": "viability-prediction",
        "year_observed": "1995",
        "metric_name": "Next challenge for 3Com — uplink flexibility",
        "metric_value": "3Com must deliver Fast Ethernet and ATM uplink promise to maintain leadership; density improvements also expected",
        "confidence": "medium",
        "methodology_code": "expert-opinion",
        "source_page": "p.3 Conclusion",
        "notes": "Aberdeen frames this as the critical next step: 'deliver the promise of uplink flexibility to assure that users can take advantage of the full gamut of high-speed server connectivity.'",
    },
]

with open(f"{OUT}/observations.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=[
        "obs_id","study_id","entity_id","tech_id","observation_type",
        "year_observed","metric_name","metric_value","confidence",
        "methodology_code","source_page","notes"
    ])
    w.writeheader()
    w.writerows(observations)
print("observations.csv written")

# ── codes.csv ─────────────────────────────────────────────────────────────────
codes = [
    # observation_type codes
    {"code_id": "strategy-classification", "code_type": "observation_type", "label": "Strategy Classification", "definition": "Categorization of an entity's business strategy"},
    {"code_id": "viability-prediction",    "code_type": "observation_type", "label": "Viability Prediction",    "definition": "Expert prediction of entity's or technology's future state or survival"},
    {"code_id": "actual-outcome",          "code_type": "observation_type", "label": "Actual Outcome",          "definition": "Verified historical outcome for an entity or technology"},
    {"code_id": "technology-assessment",   "code_type": "observation_type", "label": "Technology Assessment",   "definition": "Evaluation of a technology's maturity, architecture, or fitness for purpose"},
    {"code_id": "benchmark-result",        "code_type": "observation_type", "label": "Benchmark Result",        "definition": "Quantitative or qualitative comparison against peers or standards"},
    {"code_id": "framework-factor",        "code_type": "observation_type", "label": "Framework Factor",        "definition": "One component of a multi-factor analytical framework (e.g., HPSN stages)"},
    {"code_id": "market-data",             "code_type": "observation_type", "label": "Market Data",             "definition": "Quantitative or factual market statistic or position"},
    {"code_id": "expert-opinion",          "code_type": "observation_type", "label": "Expert Opinion",          "definition": "Qualitative professional judgment by Aberdeen analysts or cited users"},
    # methodology codes
    {"code_id": "industry-analysis",       "code_type": "methodology", "label": "Industry Analysis",       "definition": "Systematic analysis of industry structure and competitive dynamics"},
    {"code_id": "competitive-profiling",   "code_type": "methodology", "label": "Competitive Profiling",   "definition": "Detailed comparison of competing products, entities, or strategies"},
    {"code_id": "benchmarking",            "code_type": "methodology", "label": "Benchmarking",            "definition": "Comparison against industry standards or peers using quantitative metrics"},
    {"code_id": "field-research",          "code_type": "methodology", "label": "Field Research",          "definition": "Primary data collection via on-site visits, interviews, or surveys"},
    {"code_id": "document-review",         "code_type": "methodology", "label": "Document Review",         "definition": "Analysis of existing documents, specifications, and records"},
    {"code_id": "statistical-analysis",    "code_type": "methodology", "label": "Statistical Analysis",    "definition": "Quantitative data analysis with statistical methods"},
    {"code_id": "product-profiling",       "code_type": "methodology", "label": "Product Profiling",       "definition": "Structured evaluation of a specific product's features, architecture, and market position"},
    {"code_id": "user-research",           "code_type": "methodology", "label": "User Research",           "definition": "Primary research via interviews and site visits with actual product users"},
    # confidence codes
    {"code_id": "high",     "code_type": "confidence", "label": "High Confidence",   "definition": "Strong evidentiary basis; multiple corroborating sources or direct measurement"},
    {"code_id": "medium",   "code_type": "confidence", "label": "Medium Confidence", "definition": "Reasonable basis but limited corroboration; directional with some evidence"},
    {"code_id": "low",      "code_type": "confidence", "label": "Low Confidence",    "definition": "Directional judgment with limited evidence; speculative"},
    {"code_id": "verified", "code_type": "confidence", "label": "Verified",          "definition": "Confirmed by subsequent events or independent sources"},
    # lifecycle codes
    {"code_id": "emerging",         "code_type": "lifecycle", "label": "Emerging",         "definition": "Technology newly introduced; limited deployment; rapidly evolving"},
    {"code_id": "mature",           "code_type": "lifecycle", "label": "Mature",           "definition": "Technology widely deployed; standards stable; well-understood"},
    {"code_id": "declining",        "code_type": "lifecycle", "label": "Declining",        "definition": "Technology losing market share; being superseded by newer alternatives"},
    {"code_id": "obsolete",         "code_type": "lifecycle", "label": "Obsolete",         "definition": "Technology no longer in active commercial use or development"},
    {"code_id": "legacy-supported", "code_type": "lifecycle", "label": "Legacy-Supported", "definition": "Technology no longer evolving but still maintained for backward compatibility"},
    {"code_id": "active",           "code_type": "lifecycle", "label": "Active",           "definition": "Technology in active development and broad current deployment"},
]

with open(f"{OUT}/codes.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=["code_id","code_type","label","definition"])
    w.writeheader()
    w.writerows(codes)
print("codes.csv written")

print("\nAll CSV files written successfully.")
print(f"  studies.csv:      1 row")
print(f"  entities.csv:     {len(entities)} rows")
print(f"  technologies.csv: {len(technologies)} rows")
print(f"  observations.csv: {len(observations)} rows")
print(f"  codes.csv:        {len(codes)} rows")
