#!/usr/bin/env python3
"""
Build Frictionless Data Package for:
  aberdeen-1995-digital-multia
  Digital's Multia Enterprise Client: Finally Someone Listened
  Aberdeen Group, December 1995
"""
import csv
import json
import os
from pathlib import Path

STUDY_ID = "aberdeen-1995-digital-multia"
BASE = Path("/home/user/workspace/output/aberdeen-1995-digital-multia")
DATA = BASE / "data"
SCHEMA = BASE / "schema"
SCRIPTS = BASE / "scripts"

for d in [DATA, SCHEMA, SCRIPTS]:
    d.mkdir(parents=True, exist_ok=True)

ABSTRACT = (
    "This Aberdeen Group product profile evaluates Digital Equipment Corporation's Multia "
    "'enterprise client' desktop, introduced in late 1995 with both Alpha 64-bit RISC and "
    "Intel Pentium 100 models. The study employs product profiling, technology assessment, "
    "and competitive analysis to position Multia as a turn-key universal client that "
    "addresses the longstanding IS requirement for a single desktop capable of simultaneously "
    "accessing mainframes, Unix servers, PC servers, and the World Wide Web via pre-configured "
    "emulators and multiple communications protocols. Key findings include that Multia is priced "
    "$500–$800 above a comparable PC but justifies the premium through integrated interoperability, "
    "centralized IS desktop management, pre-configured terminal emulators (3270, VT 340/420, "
    "Netscape Navigator, Rumba, Kea!), a photo-album-size footprint, and chip-upgradeable "
    "dual Alpha/Intel architecture. Aberdeen concludes that Digital is the only major computer "
    "vendor that listened to enterprise IS requirements and predicts that Multia's centralized "
    "management capabilities will meaningfully reduce IS staffing and support costs at remote "
    "sites, and that the new 'market-oriented Digital' has finally arrived as a credible "
    "enterprise client vendor."
)

# ── studies.csv ──────────────────────────────────────────────────────────────
studies = [
    {
        "study_id": STUDY_ID,
        "title": "Digital's Multia Enterprise Client: Finally Someone Listened",
        "author": "Aberdeen Group",
        "date": "1995-12-01",
        "type": "product-profile",
        "subject_domain": "enterprise-desktop-computing",
        "methodology": "product-profiling, technology-assessment, competitive-analysis",
        "source_file": "1995-cs-Digital_s-Multia-Enterprise-Client_-Finally-Someone-Listened-pr-4.pdf",
        "abstract": ABSTRACT,
        "license": "CC-BY-4.0",
    }
]

with open(DATA / "studies.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(studies[0].keys()))
    w.writeheader()
    w.writerows(studies)
print(f"studies.csv: {len(studies)} rows")

# ── entities.csv ─────────────────────────────────────────────────────────────
entities = [
    {
        "entity_id": "digital-equipment-corporation",
        "entity_name": "Digital Equipment Corporation",
        "entity_type": "company",
        "sector": "enterprise-computing",
        "status": "acquired",
        "successor": "Compaq (1998) -> Hewlett-Packard (2002)",
        "years_active": "1957-1998",
        "study_id": STUDY_ID,
        "notes": "Headquartered at 200 Forest Street, Marlboro, MA 01752; creator and vendor of Multia; acquired by Compaq 1998, then HP 2002",
    },
    {
        "entity_id": "microsoft",
        "entity_name": "Microsoft Corporation",
        "entity_type": "company",
        "sector": "software",
        "status": "active",
        "successor": "",
        "years_active": "1975-present",
        "study_id": STUDY_ID,
        "notes": "Supplier of Windows NT Workstation 3.51 and Windows 95, both used on Multia",
    },
    {
        "entity_id": "netscape",
        "entity_name": "Netscape Communications Corporation",
        "entity_type": "company",
        "sector": "internet-software",
        "status": "acquired",
        "successor": "AOL (1999); browser discontinued 2008",
        "years_active": "1994-1999",
        "study_id": STUDY_ID,
        "notes": "Provided Netscape Navigator bundled as the Multia web browser; acquired by AOL 1999",
    },
    {
        "entity_id": "wall-data",
        "entity_name": "Wall Data Incorporated",
        "entity_type": "company",
        "sector": "terminal-emulation-software",
        "status": "acquired",
        "successor": "NetManage (2003); dissolved",
        "years_active": "1982-2003",
        "study_id": STUDY_ID,
        "notes": "Maker of Rumba terminal emulator, bundled with Multia as an Information Access product",
    },
    {
        "entity_id": "attachmate",
        "entity_name": "Attachmate Corporation",
        "entity_type": "company",
        "sector": "terminal-emulation-software",
        "status": "acquired",
        "successor": "Micro Focus (2014) -> OpenText (2023)",
        "years_active": "1982-2014",
        "study_id": STUDY_ID,
        "notes": "Maker of Kea! terminal emulator, bundled with Multia as an Information Access product",
    },
    {
        "entity_id": "ibm",
        "entity_name": "IBM Corporation",
        "entity_type": "company",
        "sector": "enterprise-computing",
        "status": "active",
        "successor": "",
        "years_active": "1911-present",
        "study_id": STUDY_ID,
        "notes": "Referenced as supplier of NetBEUI LAN protocol and IBM mainframes accessed via 3270 emulation",
    },
    {
        "entity_id": "novell",
        "entity_name": "Novell, Inc.",
        "entity_type": "company",
        "sector": "network-software",
        "status": "acquired",
        "successor": "Micro Focus (2014) -> OpenText (2023)",
        "years_active": "1983-2014",
        "study_id": STUDY_ID,
        "notes": "Supplier of IPX/SPX network protocol supported in Multia communications stack",
    },
    {
        "entity_id": "aberdeen-group",
        "entity_name": "Aberdeen Group",
        "entity_type": "firm",
        "sector": "technology-research",
        "status": "acquired",
        "successor": "Harte-Hanks (2001) -> Aberdeen Group brand reacquired by various entities",
        "years_active": "1988-present",
        "study_id": STUDY_ID,
        "notes": "Author and publisher of this product profile; headquartered at One Boston Place, Boston, MA 02108",
    },
]

with open(DATA / "entities.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(entities[0].keys()))
    w.writeheader()
    w.writerows(entities)
print(f"entities.csv: {len(entities)} rows")

# ── technologies.csv ──────────────────────────────────────────────────────────
technologies = [
    {
        "tech_id": "multia",
        "tech_name": "Digital Multia (Universal Client)",
        "category": "platform",
        "vendor": "Digital Equipment Corporation",
        "era": "1994-1997",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Compact all-in-one enterprise desktop; photo-album footprint; discontinued ~1997",
    },
    {
        "tech_id": "alpha-64bit-risc",
        "tech_name": "Alpha 64-bit RISC Processor",
        "category": "platform",
        "vendor": "Digital Equipment Corporation",
        "era": "1992-2004",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "One of two Multia hardware architectures; DEC Alpha architecture discontinued by HP 2004",
    },
    {
        "tech_id": "intel-pentium-100",
        "tech_name": "Intel Pentium 100 / Intel 100",
        "category": "platform",
        "vendor": "Intel",
        "era": "1994-1997",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Newly announced Intel model of Multia at time of study; 100 MHz Pentium",
    },
    {
        "tech_id": "windows-nt-3-51",
        "tech_name": "Microsoft Windows NT Workstation 3.51",
        "category": "platform",
        "vendor": "Microsoft",
        "era": "1995-1997",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Base OS for Multia; provided multitasking and stability; succeeded by Windows NT 4.0 in 1996",
    },
    {
        "tech_id": "windows-95",
        "tech_name": "Microsoft Windows 95",
        "category": "platform",
        "vendor": "Microsoft",
        "era": "1995-2001",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Supported as downloadable application environment on Multia desktop",
    },
    {
        "tech_id": "tcp-ip",
        "tech_name": "TCP/IP",
        "category": "protocol",
        "vendor": "IETF (open standard)",
        "era": "1974-present",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "active",
        "study_id": STUDY_ID,
        "notes": "Described as 'one of the most common peer-to-peer protocols' and primary Internet access protocol on Multia",
    },
    {
        "tech_id": "ipx-spx",
        "tech_name": "IPX/SPX",
        "category": "protocol",
        "vendor": "Novell",
        "era": "1983-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Novell network protocol included in Multia communications stack",
    },
    {
        "tech_id": "decnet",
        "tech_name": "DECnet",
        "category": "protocol",
        "vendor": "Digital Equipment Corporation",
        "era": "1975-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "DEC peer-to-peer proprietary protocol supported by Multia",
    },
    {
        "tech_id": "lat",
        "tech_name": "LAT (Local Area Transport)",
        "category": "protocol",
        "vendor": "Digital Equipment Corporation",
        "era": "1985-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Optimized terminal access protocol used for termserver support on Multia",
    },
    {
        "tech_id": "netbeui",
        "tech_name": "NetBEUI",
        "category": "protocol",
        "vendor": "IBM / Microsoft",
        "era": "1985-2001",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "IBM LAN protocol included in Multia transport stack",
    },
    {
        "tech_id": "x-serial-line-protocol",
        "tech_name": "X Serial Line Protocol",
        "category": "protocol",
        "vendor": "X Consortium",
        "era": "1990-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "X session protocol for Unix environment access; included in Multia",
    },
    {
        "tech_id": "nfs",
        "tech_name": "NFS (Network File System)",
        "category": "protocol",
        "vendor": "Sun Microsystems (open standard)",
        "era": "1984-present",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "active",
        "study_id": STUDY_ID,
        "notes": "Included in the optional Multia X Server package",
    },
    {
        "tech_id": "x11-r6",
        "tech_name": "X11 R6 / X Window System",
        "category": "framework",
        "vendor": "X Consortium",
        "era": "1987-present",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "legacy-supported",
        "study_id": STUDY_ID,
        "notes": "Multia X Server supplies X11.R6 functions; Wayland gradually replacing X11 on Linux",
    },
    {
        "tech_id": "pci-bus",
        "tech_name": "PCI Bus",
        "category": "platform",
        "vendor": "Intel / PCI-SIG",
        "era": "1992-present",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "active",
        "study_id": STUDY_ID,
        "notes": "Multia features PCI system bus and optional PCI slot; evolved to PCIe",
    },
    {
        "tech_id": "pcmcia",
        "tech_name": "PCMCIA",
        "category": "platform",
        "vendor": "PCMCIA (industry consortium)",
        "era": "1990-2005",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Multia Intel model includes two PCMCIA slots",
    },
    {
        "tech_id": "scsi-ii",
        "tech_name": "SCSI-II",
        "category": "platform",
        "vendor": "ANSI standard",
        "era": "1994-2003",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "External storage interface included on Multia Intel model",
    },
    {
        "tech_id": "3270-terminal-emulation",
        "tech_name": "IBM 3270 Terminal Emulation",
        "category": "application",
        "vendor": "IBM / various",
        "era": "1971-present",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "legacy-supported",
        "study_id": STUDY_ID,
        "notes": "Pre-configured on Multia for IBM mainframe access; provided via Rumba (Wall Data) and Kea! (Attachmate)",
    },
    {
        "tech_id": "vt-340-420-terminal-emulation",
        "tech_name": "VT 340/420 Terminal Emulation",
        "category": "application",
        "vendor": "Digital Equipment Corporation",
        "era": "1988-present",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "legacy-supported",
        "study_id": STUDY_ID,
        "notes": "Embedded VT terminal emulation for DEC host access; pre-configured on Multia",
    },
    {
        "tech_id": "netscape-navigator",
        "tech_name": "Netscape Navigator",
        "category": "application",
        "vendor": "Netscape Communications Corporation",
        "era": "1994-2008",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Bundled as embedded web browser on Multia for World Wide Web access",
    },
    {
        "tech_id": "rumba",
        "tech_name": "Rumba (Wall Data)",
        "category": "application",
        "vendor": "Wall Data Incorporated",
        "era": "1988-2003",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Described as 'industry leading' 3270/mainframe emulator; pre-configured on Multia",
    },
    {
        "tech_id": "kea",
        "tech_name": "Kea! (Attachmate)",
        "category": "application",
        "vendor": "Attachmate Corporation",
        "era": "1990-2014",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Terminal emulator (VT/3270) bundled with Multia; Attachmate acquired by Micro Focus 2014",
    },
    {
        "tech_id": "s3-pci-graphics",
        "tech_name": "S3 PCI Graphics Accelerator",
        "category": "platform",
        "vendor": "S3 Incorporated",
        "era": "1994-1998",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "Featured in Multia Intel model with 2 MB VRAM",
    },
    {
        "tech_id": "vram",
        "tech_name": "VRAM (Video RAM)",
        "category": "platform",
        "vendor": "various",
        "era": "1986-2000",
        "lifecycle_at_study": "mature",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "2 MB VRAM on Multia Intel S3 graphics card",
    },
    {
        "tech_id": "multia-x-server",
        "tech_name": "Multia X Server (Digital)",
        "category": "application",
        "vendor": "Digital Equipment Corporation",
        "era": "1994-1997",
        "lifecycle_at_study": "emerging",
        "lifecycle_current": "obsolete",
        "study_id": STUDY_ID,
        "notes": "DEC-supplied X11.R6 server enabling Unix application access; includes NFS in optional configuration",
    },
]

with open(DATA / "technologies.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(technologies[0].keys()))
    w.writeheader()
    w.writerows(technologies)
print(f"technologies.csv: {len(technologies)} rows")

# ── observations.csv ──────────────────────────────────────────────────────────
SID = STUDY_ID
observations = [
    # --- Market positioning ---
    {
        "obs_id": f"{SID}-OBS-001",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "strategy-classification",
        "year_observed": 1995,
        "metric_name": "product-positioning",
        "metric_value": "turn-key universal enterprise client desktop; NOT positioned as a personal computer",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Market Position",
        "notes": "Focus on packaging, integrated interoperability, and desktop management — not underlying PC architecture",
    },
    {
        "obs_id": f"{SID}-OBS-002",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "benchmark-result",
        "year_observed": 1995,
        "metric_name": "price-premium-over-comparable-pc",
        "metric_value": "$500–$800 above comparable PC desktop (depending on options)",
        "confidence": "high",
        "methodology_code": "competitive-analysis",
        "source_page": "p.1 Market Position",
        "notes": "Aberdeen states margins are 'readily justifiable' given IS cost savings and efficiencies",
    },
    {
        "obs_id": f"{SID}-OBS-003",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "physical-footprint",
        "metric_value": "approximately the size of a family photo album",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "Tightly integrated graphics, audio, and Ethernet within base platform enables compact form factor",
    },
    {
        "obs_id": f"{SID}-OBS-004",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "dual-architecture-strategy",
        "metric_value": "supports both Alpha 64-bit RISC and Intel Pentium 100 models",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "Aberdeen positions dual architecture as strategic flexibility for enterprise customers",
    },
    {
        "obs_id": f"{SID}-OBS-005",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "chip-upgradeable-design",
        "metric_value": "ZIF socket design allows processor upgrades as new architectures become available",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "Designed to extend hardware lifecycle by swapping microprocessors",
    },
    {
        "obs_id": f"{SID}-OBS-006",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "cache-memory",
        "metric_value": "256 KB standard, upgradeable to 512 KB",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "",
    },
    {
        "obs_id": f"{SID}-OBS-007",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "intel-pentium-100",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "intel-model-ram",
        "metric_value": "16 MB standard, expandable to 128 MB",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "Refers specifically to newly announced Intel 100 Multia model",
    },
    {
        "obs_id": f"{SID}-OBS-008",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "intel-pentium-100",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "intel-model-storage",
        "metric_value": "810 MB or 1 GB hard drive",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Core Product",
        "notes": "Two storage options on Intel Multia model",
    },
    {
        "obs_id": f"{SID}-OBS-009",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "windows-nt-3-51",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "operating-system",
        "metric_value": "Microsoft Windows NT Workstation 3.51; enables multitasking and stability",
        "confidence": "high",
        "methodology_code": "technology-assessment",
        "source_page": "p.2",
        "notes": "Aberdeen states NT 'makes the Multia concept and system design possible'",
    },
    {
        "obs_id": f"{SID}-OBS-010",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "communications-protocols-supported",
        "metric_value": "TCP/IP, IPX/SPX, DECnet, LAT, NetBEUI, X Serial Line Protocol; NFS in X Server option",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Six protocols pre-configured; covers mainframe, Unix, Novell, Internet, and DEC environments",
    },
    {
        "obs_id": f"{SID}-OBS-011",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "3270-terminal-emulation",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "mainframe-access-method",
        "metric_value": "IBM 3270 terminal emulation pre-configured via Rumba (Wall Data) and Kea! (Attachmate)",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Described as 'industry leading' — no manual setup required by end-user",
    },
    {
        "obs_id": f"{SID}-OBS-012",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "vt-340-420-terminal-emulation",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "dec-host-access-method",
        "metric_value": "embedded VT 340/420 terminal emulation pre-configured for DEC/OpenVMS host access",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1",
        "notes": "",
    },
    {
        "obs_id": f"{SID}-OBS-013",
        "study_id": SID,
        "entity_id": "netscape",
        "tech_id": "netscape-navigator",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "web-access-method",
        "metric_value": "Netscape Navigator embedded pre-configured for World Wide Web access",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1",
        "notes": "Access via single icon click; no manual browser setup required",
    },
    {
        "obs_id": f"{SID}-OBS-014",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia-x-server",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "unix-access-method",
        "metric_value": "Digital-supplied X11.R6 X Server with predefined protocols, system connections, and workgroup customization",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Tight integration with Multia configuration manager is the differentiated feature",
    },
    {
        "obs_id": f"{SID}-OBS-015",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "centralized-desktop-management-capabilities",
        "metric_value": "IS admins can remotely configure desktops, control application availability, enable/disable hardware (e.g., floppy), schedule software updates, distribute software",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Aberdeen identifies this as the 'real beauty' and primary differentiator of Multia",
    },
    {
        "obs_id": f"{SID}-OBS-016",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "viability-prediction",
        "year_observed": 1995,
        "metric_name": "is-cost-reduction-prediction",
        "metric_value": "IS management and support costs will decrease; fewer remote site administrators required",
        "confidence": "medium",
        "methodology_code": "technology-assessment",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "Aberdeen predicts that centralized management reduces expensive IS staffing at remote sites",
    },
    {
        "obs_id": f"{SID}-OBS-017",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "viability-prediction",
        "year_observed": 1995,
        "metric_name": "end-user-efficiency-prediction",
        "metric_value": "End-user efficiency increases because systems are made more available through central IS management",
        "confidence": "medium",
        "methodology_code": "technology-assessment",
        "source_page": "p.1 Executive Summary",
        "notes": "",
    },
    {
        "obs_id": f"{SID}-OBS-018",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "expert-opinion",
        "year_observed": 1995,
        "metric_name": "only-vendor-that-listened",
        "metric_value": "Digital is the only computer supplier that has listened to and acted on IS enterprise client requirements",
        "confidence": "medium",
        "methodology_code": "competitive-analysis",
        "source_page": "p.1 Executive Summary",
        "notes": "Strong endorsement contrasting Digital favorably against unnamed PC makers",
    },
    {
        "obs_id": f"{SID}-OBS-019",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "",
        "observation_type": "strategy-classification",
        "year_observed": 1995,
        "metric_name": "digital-market-orientation",
        "metric_value": "New market-oriented Digital Equipment Corporation has 'finally arrived'",
        "confidence": "medium",
        "methodology_code": "competitive-analysis",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "Implies previous DEC was engineering-driven and not market-responsive",
    },
    {
        "obs_id": f"{SID}-OBS-020",
        "study_id": SID,
        "entity_id": "",
        "tech_id": "multia",
        "observation_type": "market-data",
        "year_observed": 1995,
        "metric_name": "enterprise-client-market-definition",
        "metric_value": "Organizations requiring turn-key access to multiple server types: multiple transports, diverse apps (Windows, Unix X, VT, 3270), and centralized IS configuration management",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Market Position",
        "notes": "Aberdeen's three-criterion definition of the 'enterprise client' market",
    },
    {
        "obs_id": f"{SID}-OBS-021",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "universal-client-concept",
        "metric_value": "Single desktop device provides simultaneous access to mainframes, Unix servers, PC servers, and the World Wide Web via icon clicks",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.1 Executive Summary",
        "notes": "No end-user manual configuration of communications links or terminal emulators",
    },
    {
        "obs_id": f"{SID}-OBS-022",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "integration-vs-diy-stability",
        "metric_value": "DIY assembly of equivalent third-party emulators and protocols would be less stable and less robust than integrated Multia",
        "confidence": "medium",
        "methodology_code": "competitive-analysis",
        "source_page": "p.1 Market Position",
        "notes": "Aberdeen's justification for the premium price point",
    },
    {
        "obs_id": f"{SID}-OBS-023",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "floppy-disable-feature",
        "metric_value": "IS administrators can remotely enable or disable floppy drive; important for government and financial security",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Remote floppy management cited as security differentiator for regulated sectors",
    },
    {
        "obs_id": f"{SID}-OBS-024",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "technology-assessment",
        "year_observed": 1995,
        "metric_name": "remote-configuration-management",
        "metric_value": "Administrators can remotely manage downed desktops, obtain system configuration info, schedule software updates, and perform software distribution",
        "confidence": "high",
        "methodology_code": "product-profiling",
        "source_page": "p.2",
        "notes": "Identified as the key feature that truly differentiates Multia from the marketplace",
    },
    {
        "obs_id": f"{SID}-OBS-025",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "expert-opinion",
        "year_observed": 1995,
        "metric_name": "is-end-user-conflict-resolution",
        "metric_value": "Multia enables IS and end-user organizations to stop working at cross purposes",
        "confidence": "medium",
        "methodology_code": "expert-opinion",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "IS gets central control; end-users get access without managing their own systems",
    },
    {
        "obs_id": f"{SID}-OBS-026",
        "study_id": SID,
        "entity_id": "",
        "tech_id": "multia",
        "observation_type": "framework-factor",
        "year_observed": 1995,
        "metric_name": "enterprise-client-pain-point-redundancy",
        "metric_value": "IS management challenge: hardware and software inventory redundancy",
        "confidence": "high",
        "methodology_code": "industry-analysis",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "One of three IS management pain points Aberdeen identifies Multia as solving",
    },
    {
        "obs_id": f"{SID}-OBS-027",
        "study_id": SID,
        "entity_id": "",
        "tech_id": "multia",
        "observation_type": "framework-factor",
        "year_observed": 1995,
        "metric_name": "enterprise-client-pain-point-tower-of-babel",
        "metric_value": "IS management challenge: Tower-of-Babel inter-company communications from lack of standardization",
        "confidence": "high",
        "methodology_code": "industry-analysis",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "Second IS management pain point Aberdeen identifies",
    },
    {
        "obs_id": f"{SID}-OBS-028",
        "study_id": SID,
        "entity_id": "",
        "tech_id": "multia",
        "observation_type": "framework-factor",
        "year_observed": 1995,
        "metric_name": "enterprise-client-pain-point-data-security",
        "metric_value": "IS management challenge: compromised corporate data security from lax distributed computing data management",
        "confidence": "high",
        "methodology_code": "industry-analysis",
        "source_page": "p.2 Aberdeen Conclusions",
        "notes": "Third IS management pain point; Multia remote floppy disable cited as security remedy",
    },
    {
        "obs_id": f"{SID}-OBS-029",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "actual-outcome",
        "year_observed": 1997,
        "metric_name": "multia-product-discontinuation",
        "metric_value": "Multia product line discontinued approximately 1997; Alpha processor line discontinued 2004 following HP acquisition of DEC via Compaq",
        "confidence": "verified",
        "methodology_code": "document-review",
        "source_page": "post-publication",
        "notes": "Prediction of market-oriented DEC succeeding was not borne out; DEC acquired by Compaq 1998",
    },
    {
        "obs_id": f"{SID}-OBS-030",
        "study_id": SID,
        "entity_id": "digital-equipment-corporation",
        "tech_id": "multia",
        "observation_type": "actual-outcome",
        "year_observed": 1998,
        "metric_name": "digital-acquired-by-compaq",
        "metric_value": "Digital Equipment Corporation acquired by Compaq in 1998 for approximately $9.6 billion; Multia and Alpha product lines eventually discontinued",
        "confidence": "verified",
        "methodology_code": "document-review",
        "source_page": "post-publication",
        "notes": "Contradicts Aberdeen's 1995 prediction that 'market-oriented Digital has finally arrived'",
    },
]

with open(DATA / "observations.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(observations[0].keys()))
    w.writeheader()
    w.writerows(observations)
print(f"observations.csv: {len(observations)} rows")

# ── codes.csv ─────────────────────────────────────────────────────────────────
codes = [
    # Standard observation types
    {"code_id": "strategy-classification", "code_type": "observation_type", "label": "Strategy Classification", "definition": "Categorization of an entity's business strategy"},
    {"code_id": "viability-prediction", "code_type": "observation_type", "label": "Viability Prediction", "definition": "Expert prediction of entity's long-term survival or product success"},
    {"code_id": "actual-outcome", "code_type": "observation_type", "label": "Actual Outcome", "definition": "Verified historical outcome for an entity or technology after the study date"},
    {"code_id": "technology-assessment", "code_type": "observation_type", "label": "Technology Assessment", "definition": "Evaluation of a technology's maturity, fitness, or capabilities"},
    {"code_id": "benchmark-result", "code_type": "observation_type", "label": "Benchmark Result", "definition": "Quantitative comparison against peers or market standards"},
    {"code_id": "framework-factor", "code_type": "observation_type", "label": "Framework Factor", "definition": "One component of a multi-factor analytical framework"},
    {"code_id": "market-data", "code_type": "observation_type", "label": "Market Data", "definition": "Quantitative or definitional market statistic or segment characterization"},
    {"code_id": "expert-opinion", "code_type": "observation_type", "label": "Expert Opinion", "definition": "Qualitative professional judgment rendered by the study author"},
    # Standard methodology codes
    {"code_id": "industry-analysis", "code_type": "methodology", "label": "Industry Analysis", "definition": "Systematic analysis of industry structure and dynamics"},
    {"code_id": "competitive-analysis", "code_type": "methodology", "label": "Competitive Analysis", "definition": "Detailed comparison of competing entities, products, or strategies"},
    {"code_id": "benchmarking", "code_type": "methodology", "label": "Benchmarking", "definition": "Comparison against industry standards or peers"},
    {"code_id": "field-research", "code_type": "methodology", "label": "Field Research", "definition": "Primary data collection via interviews or surveys"},
    {"code_id": "document-review", "code_type": "methodology", "label": "Document Review", "definition": "Analysis of existing documents, specifications, and records"},
    {"code_id": "statistical-analysis", "code_type": "methodology", "label": "Statistical Analysis", "definition": "Quantitative data analysis with statistical methods"},
    # Study-specific methodology codes
    {"code_id": "product-profiling", "code_type": "methodology", "label": "Product Profiling", "definition": "Detailed evaluation of a single product's features, architecture, and market positioning"},
    {"code_id": "technology-assessment", "code_type": "methodology", "label": "Technology Assessment", "definition": "Structured evaluation of a technology's readiness, maturity, and suitability for enterprise use"},
    {"code_id": "expert-opinion", "code_type": "methodology", "label": "Expert Opinion", "definition": "Qualitative analytical judgment by a domain expert without formal quantitative data collection"},
    # Standard confidence levels
    {"code_id": "high", "code_type": "confidence", "label": "High Confidence", "definition": "Strong evidentiary basis; directly stated in source document or verified by independent sources"},
    {"code_id": "medium", "code_type": "confidence", "label": "Medium Confidence", "definition": "Reasonable basis but limited corroboration; analytical judgment by author"},
    {"code_id": "low", "code_type": "confidence", "label": "Low Confidence", "definition": "Directional judgment with limited evidence"},
    {"code_id": "verified", "code_type": "confidence", "label": "Verified", "definition": "Confirmed by subsequent events or independent historical sources"},
    # Lifecycle codes
    {"code_id": "emerging", "code_type": "lifecycle", "label": "Emerging", "definition": "Technology or product recently introduced; early adoption phase"},
    {"code_id": "mature", "code_type": "lifecycle", "label": "Mature", "definition": "Technology widely deployed and stable; past peak growth"},
    {"code_id": "declining", "code_type": "lifecycle", "label": "Declining", "definition": "Technology losing market share or approaching end of mainstream support"},
    {"code_id": "obsolete", "code_type": "lifecycle", "label": "Obsolete", "definition": "Technology no longer actively maintained or deployed in new systems"},
    {"code_id": "legacy-supported", "code_type": "lifecycle", "label": "Legacy Supported", "definition": "Technology maintained for backward compatibility but not recommended for new deployments"},
    {"code_id": "active", "code_type": "lifecycle", "label": "Active", "definition": "Technology currently in mainstream use and active development"},
]

with open(DATA / "codes.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=list(codes[0].keys()))
    w.writeheader()
    w.writerows(codes)
print(f"codes.csv: {len(codes)} rows")

print("\nAll CSV files written successfully.")
