#!/usr/bin/env python3
"""
Demo analysis script for: Progress Software's WebSpeed: Business Transaction Processing On The Internet
Aberdeen Group Archival Research Collection — Frictionless Data Package
Generated by Archival Ingest Skill v13
"""
import csv
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, "..", "data")

def load_csv(name):
    with open(os.path.join(DATA, name), newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def main():
    studies = load_csv("studies.csv")
    entities = load_csv("entities.csv")
    technologies = load_csv("technologies.csv")
    observations = load_csv("observations.csv")
    codes = load_csv("codes.csv")

    study = studies[0]
    print("=" * 70)
    print(f"STUDY: {study['title']}")
    print(f"  Author:     {study['author']}")
    print(f"  Date:       {study['date']}")
    print(f"  Domain:     {study['subject_domain']}")
    print(f"  Importance: {study['importance']}")
    print(f"  Relevance:  {study['relevance']}")
    print(f"  Prescience: {study['prescience']}")
    print("=" * 70)

    print(f"\nDATA SUMMARY")
    print(f"  Entities:      {len(entities)}")
    print(f"  Technologies:  {len(technologies)}")
    print(f"  Observations:  {len(observations)}")

    # Observation type breakdown
    type_counts = {}
    for o in observations:
        t = o["observation_type"]
        type_counts[t] = type_counts.get(t, 0) + 1
    print("\nOBSERVATION TYPES:")
    for t, c in sorted(type_counts.items()):
        print(f"  {t:<30} {c}")

    # Referential integrity: entity_ids in observations exist in entities
    entity_ids = {e["entity_id"] for e in entities} | {""}
    obs_entity_ids = {o["entity_id"] for o in observations}
    bad_entities = obs_entity_ids - entity_ids
    if bad_entities:
        print(f"\n[INTEGRITY WARNING] Unknown entity_ids in observations: {bad_entities}")
    else:
        print("\n[OK] Entity referential integrity: PASS")

    # Referential integrity: tech_ids
    tech_ids = {t["tech_id"] for t in technologies} | {""}
    obs_tech_ids = {o["tech_id"] for o in observations}
    bad_techs = obs_tech_ids - tech_ids
    if bad_techs:
        print(f"[INTEGRITY WARNING] Unknown tech_ids in observations: {bad_techs}")
    else:
        print("[OK] Technology referential integrity: PASS")

    # Code coverage
    code_ids = {c["code_id"] for c in codes}
    obs_types = {o["observation_type"] for o in observations}
    meth_codes = {o["methodology_code"] for o in observations}
    bad_obs_types = obs_types - code_ids
    bad_meth = meth_codes - code_ids
    if bad_obs_types:
        print(f"[INTEGRITY WARNING] Uncoded observation_types: {bad_obs_types}")
    else:
        print("[OK] Observation type code coverage: PASS")
    if bad_meth:
        print(f"[INTEGRITY WARNING] Uncoded methodology_codes: {bad_meth}")
    else:
        print("[OK] Methodology code coverage: PASS")

    # Prediction accuracy
    predictions = [o for o in observations if o["observation_type"] == "viability-prediction"]
    actuals = [o for o in observations if o["observation_type"] == "actual-outcome"]
    print(f"\nPREDICTION ANALYSIS")
    print(f"  Viability predictions: {len(predictions)}")
    print(f"  Actual outcomes:       {len(actuals)}")
    if predictions and actuals:
        print("  Prediction / Outcome pairs:")
        for p in predictions:
            paired = [a for a in actuals if a["entity_id"] == p["entity_id"] or a["tech_id"] == p["tech_id"]]
            if paired:
                for a in paired:
                    print(f"    PRED: {p['metric_name'][:50]} -> {p['metric_value'][:40]}")
                    print(f"    ACTU: {a['metric_name'][:50]} -> {a['metric_value'][:40]}")
                    print()

    print("[DONE] Validation complete.")

if __name__ == "__main__":
    main()
