#!/usr/bin/env python3
"""backfill_page_type_quotations_v1.py

Add the `page_type:` frontmatter key to the 335 quotations-corpus wiki pages
that carry only `type:` (334 wiki/quotations/quote-*.md + 1
wiki/methodology/quotations_corpus_v1.md).

ROOT CAUSE: the v1.8.0 quotations-corpus generator wrote `type: quotation`
(and `type: methodology` for the index), but the embedding/index pipeline reads
`page_type:` (reembed.py / 05_compute_embeddings_v3.py -> front.get("page_type")).
So these 335 pages showed page_type='' in embeddings.parquet, weakening
`kw ask --type` filtering. The quotations pages are NOT regenerated by the
routine Phase 3-6 pipeline (one-off generation), so this backfill is durable.

FIX: insert `page_type: <value>` immediately after the existing `type:` line,
mirroring its value. Idempotent (skips files that already have page_type).
Preserves the original `type:` line for backward compatibility. Touches ONLY
these 335 files; makes no other change.

dry-run default; --commit to write. No backup dir needed (git tracks these
pages; revert is `git checkout`), but prints a full manifest of touched files.
"""
import sys
from pathlib import Path

WIKI = Path.home() / "Repos/kastner-aberdeen-wiki/wiki"
TARGETS = sorted(WIKI.glob("quotations/quote-*.md")) + [WIKI / "methodology/quotations_corpus_v1.md"]

commit = "--commit" in sys.argv

touched, skipped, missing = [], [], []
for f in TARGETS:
    if not f.exists():
        missing.append(f); continue
    lines = f.read_text(encoding="utf-8").splitlines(keepends=True)
    # frontmatter must start at line 0 with ---
    if not lines or lines[0].strip() != "---":
        skipped.append((f, "no frontmatter")); continue
    # find end of frontmatter and the type: line within it
    fm_end = None
    type_idx = None
    has_page_type = False
    for i in range(1, len(lines)):
        s = lines[i].strip()
        if s == "---":
            fm_end = i; break
        if s.startswith("type:") and type_idx is None:
            type_idx = i
        if s.startswith("page_type:"):
            has_page_type = True
    if fm_end is None:
        skipped.append((f, "unterminated frontmatter")); continue
    if has_page_type:
        skipped.append((f, "already has page_type")); continue
    if type_idx is None:
        skipped.append((f, "no type: line")); continue
    # derive value from the type: line
    type_val = lines[type_idx].split(":", 1)[1].strip()
    new_line = f"page_type: {type_val}\n"
    lines.insert(type_idx + 1, new_line)
    touched.append((f, type_val))
    if commit:
        f.write_text("".join(lines), encoding="utf-8")

print(f"Mode: {'COMMIT' if commit else 'DRY-RUN'}")
print(f"Targets: {len(TARGETS)}  Touched: {len(touched)}  Skipped: {len(skipped)}  Missing: {len(missing)}")
# summarize touched by value
from collections import Counter
byval = Counter(v for _, v in touched)
print("Touched by page_type value:", dict(byval))
if skipped:
    print(f"\nSkipped ({len(skipped)}):")
    for f, why in skipped[:10]:
        print(f"  {f.name}: {why}")
    if len(skipped) > 10:
        print(f"  ... +{len(skipped)-10} more")
if missing:
    print(f"\nMISSING: {[str(m) for m in missing]}")
if not commit:
    print("\nDRY-RUN only — pass --commit to write. Then re-embed (Phase 5) so embeddings.parquet picks up page_type.")
else:
    print("\nWROTE. Next: re-embed (Phase 5 / kw rebuild-embeddings) so embeddings.parquet reflects the new page_type.")
