#!/usr/bin/env python3
"""generate_archive_stats.py — SINGLE SOURCE OF TRUTH for archive counts.

Reads the live DuckDB (read-only) and writes ARCHIVE_STATS.md at the archive
repo root. Every count the archive quotes lives HERE and nowhere else. READMEs
and release notes link to this file instead of hard-coding numbers.

Regenerate after any masters/rebuild change (wire into the pipeline as a final
step, or run standalone). Read-only; only writes ARCHIVE_STATS.md (+ .json).

Usage:
  python3 generate_archive_stats.py                 # write ARCHIVE_STATS.md + .json
  python3 generate_archive_stats.py --print         # also echo to stdout
  python3 generate_archive_stats.py --db PATH --out PATH
"""
import duckdb, json, sys, argparse, datetime
from pathlib import Path

DEF_DB  = Path.home()/"Repos/kastner-aberdeen-wiki/db/kastner.duckdb"
DEF_OUT = Path.home()/"Desktop/Archive/aberdeen-group-archive/ARCHIVE_STATS.md"

ap = argparse.ArgumentParser()
ap.add_argument("--db", default=str(DEF_DB))
ap.add_argument("--out", default=str(DEF_OUT))
ap.add_argument("--print", action="store_true", dest="echo")
a = ap.parse_args()

con = duckdb.connect(a.db, read_only=True)
def one(sql): return con.execute(sql).fetchone()[0]

S = {}
# corpus shape
S["studies"]        = one("SELECT COUNT(*) FROM v_studies")
S["observations"]   = one("SELECT COUNT(*) FROM v_observations")
S["entities"]       = one("SELECT COUNT(*) FROM v_entities")
S["technologies"]   = one("SELECT COUNT(*) FROM v_technologies")
S["decades"]        = one("SELECT COUNT(DISTINCT (CAST(pub_year AS INTEGER)//10)*10) FROM v_studies WHERE pub_year IS NOT NULL")
S["year_min"]       = one("SELECT MIN(CAST(pub_year AS INTEGER)) FROM v_studies WHERE pub_year IS NOT NULL")
S["year_max"]       = one("SELECT MAX(CAST(pub_year AS INTEGER)) FROM v_studies WHERE pub_year IS NOT NULL")
# long-horizon prescience
S["lh_scores"]      = one("SELECT COUNT(*) FROM v_prescience_raw")
S["lh_obs_scored"]  = one("SELECT COUNT(*) FROM v_observations_with_prescience")
S["enum_high"]      = one("SELECT COUNT(*) FROM v_studies WHERE study_prescience_enum='high'")
S["enum_medium"]    = one("SELECT COUNT(*) FROM v_studies WHERE study_prescience_enum='medium'")
S["enum_low"]       = one("SELECT COUNT(*) FROM v_studies WHERE study_prescience_enum='low'")
S["enum_na"]        = one("SELECT COUNT(*) FROM v_studies WHERE study_prescience_enum='not-applicable'")
S["view_high_max4"] = one("SELECT COUNT(*) FROM v_studies_with_high_prescience")
S["tight_mean35"]   = one("SELECT COUNT(*) FROM v_studies WHERE prescience_mean >= 3.5")
# short-horizon
S["sh_scores"]      = one("SELECT COUNT(*) FROM v_prescience_sh")
S["sh_verdicts"]    = one("SELECT COUNT(*) FROM v_studies_with_sh_verdicts")
# embedding index (parquet may be gitignored but is on disk)
try:
    ep = Path(a.db).parent.parent/"data"/"embeddings.parquet"
    S["embed_pages"] = one(f"SELECT COUNT(*) FROM read_parquet('{ep}')")
except Exception:
    S["embed_pages"] = None
con.close()

ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

md = f"""# Archive Stats — canonical counts

<!-- GENERATED by scripts/generate_archive_stats.py from the live DuckDB.
     DO NOT hand-edit. Do NOT copy these numbers into prose elsewhere —
     link to this file instead. Regenerate after every masters/rebuild change. -->

_Generated {ts} from `db/kastner.duckdb`._

## Corpus shape
| Metric | Count |
|---|---:|
| Studies | {S['studies']:,} |
| Observations | {S['observations']:,} |
| Entity rows | {S['entities']:,} |
| Technology rows | {S['technologies']:,} |
| Decades covered | {S['decades']} ({S['year_min']}–{S['year_max']}) |

## Long-horizon (holistic) prescience
| Metric | Count |
|---|---:|
| Observation-level scores (`_master_prescience_scores.csv`) | {S['lh_scores']:,} |
| Observations carrying a long-horizon score | {S['lh_obs_scored']:,} |
| Verdict enum = high | {S['enum_high']:,} |
| Verdict enum = medium | {S['enum_medium']:,} |
| Verdict enum = low | {S['enum_low']:,} |
| Verdict enum = not-applicable | {S['enum_na']:,} |
| `prescience_max ≥ 4` (loose view, `v_studies_with_high_prescience`) | {S['view_high_max4']:,} |
| `prescience_mean ≥ 3.5` (tight) | {S['tight_mean35']:,} |

The **enum** is the Rule-A mean verdict (the scorer makes the call; not hand-overridden).
The **loose view** flags studies with any single obs scored 4–5. The **tight** surface is
the strictest mean threshold. They measure different things — pick per your question.

## Short-horizon prescience (3y / 5y)
| Metric | Count |
|---|---:|
| Short-horizon observation scores (`_master_prescience_short_horizon.csv`) | {S['sh_scores']:,} |
| Studies with rolled-up 3y/5y verdicts | {S['sh_verdicts']:,} |

## Wiki
| Metric | Count |
|---|---:|
| Embedding index pages (bge-m3, 1024-dim) | {S['embed_pages']:,} |
"""

Path(a.out).write_text(md)
Path(a.out).with_suffix(".json").write_text(json.dumps({"generated_utc": ts, **S}, indent=2))
print(f"WROTE {a.out}")
print(f"WROTE {Path(a.out).with_suffix('.json')}")
if a.echo:
    print("\n"+md)
